name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: build production project
        run: yarn build:prod
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: linting typescript
        run: yarn lint:ts
      - name: unit testing
        run: yarn unit
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: unit testing
        run: yarn unit
